baseURL = "https://3HLD.github.io/"
languageCode = "en"
title = "3HLD"
description = "3HLD"
theme = "bytethecookies-theme"
defaultContentLanguage = "en"
enableEmoji = false 
paginate = 5
enableGitInfo = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]


[params.categoryEmojis]
Web = "ğŸŒ"
Netw = "ğŸ“¡"
Pwn = "ğŸ’»"
Crypto = "ğŸ”"
Forensic = "ğŸ•µï¸"
Osint = "ğŸ”"
Misc = "ğŸ”§"
Rev = "ğŸ”¨"
Block = "ğŸ”—"


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
[params]
math = true
