[[navbar]]
identifier = "about"
name = "ğŸ’» About"
url = "/"
weight = 1
[[navbar]]
identifier = "news"
name = "ğŸ“° News"
url = "/news/"
weight = 2
[[navbar]]
identifier = "writeups"
name = "ğŸ“‘ Writeups"
url = "/writeups/"
weight = 3

